# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        uses: appleboy/scp-action@master
        #run: echo Hello, world!
        env:
         HOST: 178.128.96.207
         USERNAME: root
         PORT: 22
         KEY: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAux5kVsmiNiWSe+zoaZJaUpW7wUb0ER6NtXbNutthuiKOYTwFo8T0
wPkpYFELnPg0xcPfDUYb5pROZaVgaMu6yhRgin2zHSKRxCZlko1PIqUn6tQRG1o2Jhhe63
is7QxFjhilRZLp+Joe5cPfSO9c4aSxdDfWo9ZTzwZPtFug9yJuh79V8hYRplt2ASAdSZB4
6/UdCZA5z69shjLGK7mvymTs2KHCH07R15MZla6j6EjV64XDAotU11jFL0/zOlawMGRi/Q
0PJG1SYJbpbbkEWSwP6fewTTzq/jvfw2aT1oNMk9v8FGjPS3V7Rn21gNQPb6llifEsOwGF
T4mV+ed/wgMMFeUV5hKPcu5CFFGva///kge0NOVCxURJubGNqqjGLucOUL/GtDordoEKhn
3LLGPV9mK8dR2YhjAgTMqiHmuNSTwuxE5HMcSdHxyTRnQaWMO1SmcPi1288UKvOxjMBeIi
79RlvuJC8P5nmINM0nGKafn2k6FlYbapWO4WqaeX50hnqM9HGyGHgd62jFosehdI2AKTV2
OCh+i5kfmf6kWviioapypG/jHQlo9g5QXp4P4H6bymWa0JMiv7+ZcyZB90hFXoA+IBWCyf
zP/sDFY04LnkvhxwkcLUB2tv8znd7jgWNbZqj6mXv6sWjkIrJ76YQLBYp1L4ERcqaUc+YX
MAAAdQDzM87Q8zPO0AAAAHc3NoLXJzYQAAAgEAux5kVsmiNiWSe+zoaZJaUpW7wUb0ER6N
tXbNutthuiKOYTwFo8T0wPkpYFELnPg0xcPfDUYb5pROZaVgaMu6yhRgin2zHSKRxCZlko
1PIqUn6tQRG1o2Jhhe63is7QxFjhilRZLp+Joe5cPfSO9c4aSxdDfWo9ZTzwZPtFug9yJu
h79V8hYRplt2ASAdSZB46/UdCZA5z69shjLGK7mvymTs2KHCH07R15MZla6j6EjV64XDAo
tU11jFL0/zOlawMGRi/Q0PJG1SYJbpbbkEWSwP6fewTTzq/jvfw2aT1oNMk9v8FGjPS3V7
Rn21gNQPb6llifEsOwGFT4mV+ed/wgMMFeUV5hKPcu5CFFGva///kge0NOVCxURJubGNqq
jGLucOUL/GtDordoEKhn3LLGPV9mK8dR2YhjAgTMqiHmuNSTwuxE5HMcSdHxyTRnQaWMO1
SmcPi1288UKvOxjMBeIi79RlvuJC8P5nmINM0nGKafn2k6FlYbapWO4WqaeX50hnqM9HGy
GHgd62jFosehdI2AKTV2OCh+i5kfmf6kWviioapypG/jHQlo9g5QXp4P4H6bymWa0JMiv7
+ZcyZB90hFXoA+IBWCyfzP/sDFY04LnkvhxwkcLUB2tv8znd7jgWNbZqj6mXv6sWjkIrJ7
6YQLBYp1L4ERcqaUc+YXMAAAADAQABAAACAQC3kdtSIUHX6QhKN2LSn1epCWhG9vreCKFx
UvoFxM+dMeWIkr/dqI2M+2OSMDA6cG4lTkF23j7k+L3ojlOEu8mmElObyjF79bwXOKwRGD
x4eposkJuvv9K7kNEeJSdQ7ucVviv1k2miEGEbfAuDm//9BftpTpZt6QgTY9ex0uqZSNgy
qI0CkJAEKlocRIs27lsS8UbpaOquSyUmio1LvEEvR8/rvtWYrVTELnW9GLWIXlwvUOy9hD
9ZfKcGAWNW6lCzSOir5LHkRLO6OpMKp6YSbV23ZN07CPZpMAgXxHxoyCrKK9ijlSc4miq0
PwNfPatfGkqZB1cjFBzaqNnPb0MvPlDDRCxxatC+syrAYZJymFuEy5UQAT7G2sjEvTgfYu
5EsQG7HkqxZ84e2CtbFkLhWLdfHBho+AOEjvZgzIlLTFZGrMQEtpW7J5LrXlJl8jlkYDYw
VO2teLX92bgUA9LB7QehMRhPB3d3V7YWuKTEn5tAfqunbmg2sH0f9N/iRxXXXrGZmnaXuO
sqH2d9fUq+gSQPv8aZjSt8ZONq1HuBqQQxNTyNt4Xzzj4mCICX0SZXICtHmCKEgY3eB6OB
AHpZyuKgcECDERCJJCXMNOjdXc6VFj5g8px723oOpkTg5Is3nyYRBS0Y6pTeNrsScvOA7H
AB3oDxxklTm+lD+zFQoQAAAQB+Fe/pZGbYDsZRrsdkO+VJe+EISdsdyGT6pgLbpwVVWerj
DL3QmcrcBkEmCI/rwOn8LXsy2LhRaHog4Qs9sMOldZKPaWmKW4PP1J25m0lYxDNW+OTRNB
F4d1DXFnHBhEHnC1EddgJvyNvbKN/IpUke6GpTeHPDxxmReBPKATgmCdXv0GNMFF0Xgarp
FjDZodRK/IDA+VkeCjnWGwD1uF7g7dV6yMdaxJXEaORal6XKTnjtLpfqqjjKThohFacNY1
Au/3IoQoXd8SoTvcame9ywjPimAWR9wA28vK1Vn6kOWFt6ENbwR4PZfNo8MKLZGfdWew3z
JyNBqYaZX5P4RPYxAAABAQDpEuaZpjZ7DjJfExbpM+Awg0/9E6MREPJaKZzoagCgk0Tgx7
6XT453+ETX3/sckkDtYXPkilDmr+WHIicdNihkYIMIdwC2Rn2dOjBeZ5Ra7LBny44tzWQA
n8CcBunxxD8gTmdt8mhZzGetkJ4HpPZ//Y2wrmW3nRQYJKqAfyszUUAHo1KW8TlTZkPMzG
EruZmgmgsfnt8/ALOj+R+OTerPNE4jbggoN/oqY8gLAuHbMFC1gcUOnjb1Tyy24VY8oG/G
2W9/UWB8EqSy3b7NnrBYxVVkMOAhQinNYF0CuU8EoUKM1EeBlDs2FpSU7YqJJY1LnU2vUr
vg/OLpgPg8MN9ZAAABAQDNhkhBmkSXHzt+s5MaafZVfEDd01qgEB9PMtouAiz0UtVCQSOu
dWmlDkXjAPJO+GbXcFBPQuqIpK5xYWd3sTIW76q5XXgK23vW3jft//m4BvwiweBNLMU4lH
rU1m8otSQY41gJFNoAhH430iq04gLNtRdd/oRvfVjeZMMgATxQbJjihiQtfQ+zSBmMJ5xg
2SjmOWJYOQ2NnLclFPzbDb4tN/FU3C7NnOcSv8rZ7oHftXYbAu5U8c/FOyps840Uhsfdkb
41a8Ye0A6ZKXmWnPPdmSI24NsN/j3RCRMmjBqsj3cwR5uUu3P2tfBPZ3N1Fg5lkPBhypVK
xduVt2TXZZmrAAAAE3B4d2Vic2hvcEBnbWFpbC5jb20BAgMEBQYH
-----END OPENSSH PRIVATE KEY-----
        with:
         source: "."
         target: "/var/www/xebagachanhphat.online"
      # Runs a set of commands using the runners shell
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: 178.128.96.207
          USERNAME: root
          PORT: 22
          KEY: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAux5kVsmiNiWSe+zoaZJaUpW7wUb0ER6NtXbNutthuiKOYTwFo8T0
wPkpYFELnPg0xcPfDUYb5pROZaVgaMu6yhRgin2zHSKRxCZlko1PIqUn6tQRG1o2Jhhe63
is7QxFjhilRZLp+Joe5cPfSO9c4aSxdDfWo9ZTzwZPtFug9yJuh79V8hYRplt2ASAdSZB4
6/UdCZA5z69shjLGK7mvymTs2KHCH07R15MZla6j6EjV64XDAotU11jFL0/zOlawMGRi/Q
0PJG1SYJbpbbkEWSwP6fewTTzq/jvfw2aT1oNMk9v8FGjPS3V7Rn21gNQPb6llifEsOwGF
T4mV+ed/wgMMFeUV5hKPcu5CFFGva///kge0NOVCxURJubGNqqjGLucOUL/GtDordoEKhn
3LLGPV9mK8dR2YhjAgTMqiHmuNSTwuxE5HMcSdHxyTRnQaWMO1SmcPi1288UKvOxjMBeIi
79RlvuJC8P5nmINM0nGKafn2k6FlYbapWO4WqaeX50hnqM9HGyGHgd62jFosehdI2AKTV2
OCh+i5kfmf6kWviioapypG/jHQlo9g5QXp4P4H6bymWa0JMiv7+ZcyZB90hFXoA+IBWCyf
zP/sDFY04LnkvhxwkcLUB2tv8znd7jgWNbZqj6mXv6sWjkIrJ76YQLBYp1L4ERcqaUc+YX
MAAAdQDzM87Q8zPO0AAAAHc3NoLXJzYQAAAgEAux5kVsmiNiWSe+zoaZJaUpW7wUb0ER6N
tXbNutthuiKOYTwFo8T0wPkpYFELnPg0xcPfDUYb5pROZaVgaMu6yhRgin2zHSKRxCZlko
1PIqUn6tQRG1o2Jhhe63is7QxFjhilRZLp+Joe5cPfSO9c4aSxdDfWo9ZTzwZPtFug9yJu
h79V8hYRplt2ASAdSZB46/UdCZA5z69shjLGK7mvymTs2KHCH07R15MZla6j6EjV64XDAo
tU11jFL0/zOlawMGRi/Q0PJG1SYJbpbbkEWSwP6fewTTzq/jvfw2aT1oNMk9v8FGjPS3V7
Rn21gNQPb6llifEsOwGFT4mV+ed/wgMMFeUV5hKPcu5CFFGva///kge0NOVCxURJubGNqq
jGLucOUL/GtDordoEKhn3LLGPV9mK8dR2YhjAgTMqiHmuNSTwuxE5HMcSdHxyTRnQaWMO1
SmcPi1288UKvOxjMBeIi79RlvuJC8P5nmINM0nGKafn2k6FlYbapWO4WqaeX50hnqM9HGy
GHgd62jFosehdI2AKTV2OCh+i5kfmf6kWviioapypG/jHQlo9g5QXp4P4H6bymWa0JMiv7
+ZcyZB90hFXoA+IBWCyfzP/sDFY04LnkvhxwkcLUB2tv8znd7jgWNbZqj6mXv6sWjkIrJ7
6YQLBYp1L4ERcqaUc+YXMAAAADAQABAAACAQC3kdtSIUHX6QhKN2LSn1epCWhG9vreCKFx
UvoFxM+dMeWIkr/dqI2M+2OSMDA6cG4lTkF23j7k+L3ojlOEu8mmElObyjF79bwXOKwRGD
x4eposkJuvv9K7kNEeJSdQ7ucVviv1k2miEGEbfAuDm//9BftpTpZt6QgTY9ex0uqZSNgy
qI0CkJAEKlocRIs27lsS8UbpaOquSyUmio1LvEEvR8/rvtWYrVTELnW9GLWIXlwvUOy9hD
9ZfKcGAWNW6lCzSOir5LHkRLO6OpMKp6YSbV23ZN07CPZpMAgXxHxoyCrKK9ijlSc4miq0
PwNfPatfGkqZB1cjFBzaqNnPb0MvPlDDRCxxatC+syrAYZJymFuEy5UQAT7G2sjEvTgfYu
5EsQG7HkqxZ84e2CtbFkLhWLdfHBho+AOEjvZgzIlLTFZGrMQEtpW7J5LrXlJl8jlkYDYw
VO2teLX92bgUA9LB7QehMRhPB3d3V7YWuKTEn5tAfqunbmg2sH0f9N/iRxXXXrGZmnaXuO
sqH2d9fUq+gSQPv8aZjSt8ZONq1HuBqQQxNTyNt4Xzzj4mCICX0SZXICtHmCKEgY3eB6OB
AHpZyuKgcECDERCJJCXMNOjdXc6VFj5g8px723oOpkTg5Is3nyYRBS0Y6pTeNrsScvOA7H
AB3oDxxklTm+lD+zFQoQAAAQB+Fe/pZGbYDsZRrsdkO+VJe+EISdsdyGT6pgLbpwVVWerj
DL3QmcrcBkEmCI/rwOn8LXsy2LhRaHog4Qs9sMOldZKPaWmKW4PP1J25m0lYxDNW+OTRNB
F4d1DXFnHBhEHnC1EddgJvyNvbKN/IpUke6GpTeHPDxxmReBPKATgmCdXv0GNMFF0Xgarp
FjDZodRK/IDA+VkeCjnWGwD1uF7g7dV6yMdaxJXEaORal6XKTnjtLpfqqjjKThohFacNY1
Au/3IoQoXd8SoTvcame9ywjPimAWR9wA28vK1Vn6kOWFt6ENbwR4PZfNo8MKLZGfdWew3z
JyNBqYaZX5P4RPYxAAABAQDpEuaZpjZ7DjJfExbpM+Awg0/9E6MREPJaKZzoagCgk0Tgx7
6XT453+ETX3/sckkDtYXPkilDmr+WHIicdNihkYIMIdwC2Rn2dOjBeZ5Ra7LBny44tzWQA
n8CcBunxxD8gTmdt8mhZzGetkJ4HpPZ//Y2wrmW3nRQYJKqAfyszUUAHo1KW8TlTZkPMzG
EruZmgmgsfnt8/ALOj+R+OTerPNE4jbggoN/oqY8gLAuHbMFC1gcUOnjb1Tyy24VY8oG/G
2W9/UWB8EqSy3b7NnrBYxVVkMOAhQinNYF0CuU8EoUKM1EeBlDs2FpSU7YqJJY1LnU2vUr
vg/OLpgPg8MN9ZAAABAQDNhkhBmkSXHzt+s5MaafZVfEDd01qgEB9PMtouAiz0UtVCQSOu
dWmlDkXjAPJO+GbXcFBPQuqIpK5xYWd3sTIW76q5XXgK23vW3jft//m4BvwiweBNLMU4lH
rU1m8otSQY41gJFNoAhH430iq04gLNtRdd/oRvfVjeZMMgATxQbJjihiQtfQ+zSBmMJ5xg
2SjmOWJYOQ2NnLclFPzbDb4tN/FU3C7NnOcSv8rZ7oHftXYbAu5U8c/FOyps840Uhsfdkb
41a8Ye0A6ZKXmWnPPdmSI24NsN/j3RCRMmjBqsj3cwR5uUu3P2tfBPZ3N1Fg5lkPBhypVK
xduVt2TXZZmrAAAAE3B4d2Vic2hvcEBnbWFpbC5jb20BAgMEBQYH
-----END OPENSSH PRIVATE KEY-----
          script: ls
        #run: |
          #echo Add other actions to build,
          #echo test, and deploy your project.
